package templates

/*
256 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
257 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
258 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
259 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
260 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
261 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
262 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
263 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
264 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
265 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
266 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
267 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
268 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
269 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
270 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
271 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
272 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
273 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
274 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
275 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
276 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
277 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
278 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
279 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
280 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
281 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
282 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
283 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
284 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
285 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
286 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
287 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
288 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
289 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
290 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
291 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
292 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
293 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
294 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
295 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
296 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
297 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
298 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
299 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
300 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
301 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
302 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
303 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
304 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
305 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
306 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
307 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
308 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
309 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
310 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
311 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
312 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
313 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
314 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
315 IPFIX_PROTO_L2_ETH IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
316 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
317 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
318 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
319 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
320 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
321 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
322 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
323 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
324 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
325 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
326 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
327 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
328 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
329 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
330 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
331 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
332 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
333 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
334 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
335 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_UNKNOWN IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
336 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
337 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
338 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
339 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
340 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
341 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
342 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
343 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
344 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
345 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
346 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
347 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
348 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
349 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
350 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
351 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
352 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
353 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
354 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
355 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV4 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
356 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
357 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
358 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED INGRESS_FLOW
359 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UNKNOWN IPFIX_PROTO_TUNNELED EGRESS_FLOW
360 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
361 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
362 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED INGRESS_FLOW
363 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_TCP IPFIX_PROTO_TUNNELED EGRESS_FLOW
364 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
365 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
366 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED INGRESS_FLOW
367 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_UDP IPFIX_PROTO_TUNNELED EGRESS_FLOW
368 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
369 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
370 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED INGRESS_FLOW
371 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_SCTP IPFIX_PROTO_TUNNELED EGRESS_FLOW
372 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED INGRESS_FLOW
373 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_NOT_TUNNELED EGRESS_FLOW
374 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED INGRESS_FLOW
375 IPFIX_PROTO_L2_VLAN IPFIX_PROTO_L3_IPV6 IPFIX_PROTO_L4_ICMP IPFIX_PROTO_TUNNELED EGRESS_FLOW
*/
const (
	IPFIX_PROTO_L2_ETH  = 0
	IPFIX_PROTO_L2_VLAN = 1
	NUM_IPFIX_PROTO_L2  = 2

	IPFIX_PROTO_L3_UNKNOWN = 0
	IPFIX_PROTO_L3_IPV4    = 1
	IPFIX_PROTO_L3_IPV6    = 2
	NUM_IPFIX_PROTO_L3     = 3

	IPFIX_PROTO_L4_UNKNOWN = 0
	IPFIX_PROTO_L4_TCP     = 1
	IPFIX_PROTO_L4_UDP     = 2
	IPFIX_PROTO_L4_SCTP    = 3
	IPFIX_PROTO_L4_ICMP    = 4
	NUM_IPFIX_PROTO_L4     = 5

	IPFIX_PROTO_NOT_TUNNELED = 0
	IPFIX_PROTO_TUNNELED     = 1
	NUM_IPFIX_PROTO_TUNNEL   = 2

	INGRESS_FLOW             = 0x00
	EGRESS_FLOW              = 0x01
	NUM_IPFIX_FLOW_DIRECTION = 2
	IPFIX_TEMPLATE_ID_MIN    = 256
)

type OVSTemplate struct {
	IpfixProtoL2       int
	IpfixProtoL3       int
	IpfixProtoL4       int
	IpfixProtoTunnel   int
	IpfixFlowDirection int
}

func ParseOVSTemplateId(templateId int) OVSTemplate {
	ipfixProtoL2 := 0
	ipfixProtoL3 := 0
	ipfixProtoL4 := 0
	ipfixProtoTunnel := 0
	ipfixFlowDirection := 0
	templateId = templateId - IPFIX_TEMPLATE_ID_MIN
	// l2 protocol misc
	if templateId >= 0 && templateId <= 59 {
		ipfixProtoL2 = IPFIX_PROTO_L2_ETH
	} else {
		ipfixProtoL2 = IPFIX_PROTO_L2_VLAN
		templateId = templateId - 60
	}
	// l3 protocol misc

	if templateId >= 0 && templateId <= 19 {
		ipfixProtoL3 = IPFIX_PROTO_L3_UNKNOWN
	} else if templateId >= 20 && templateId <= 39 {
		ipfixProtoL3 = IPFIX_PROTO_L3_IPV4
		templateId = templateId - 20
	} else {
		ipfixProtoL3 = IPFIX_PROTO_L3_IPV6
		templateId = templateId - 40
	}
	//l4 protocol misc
	if templateId >= 0 && templateId <= 3 {
		ipfixProtoL4 = IPFIX_PROTO_L4_UNKNOWN
	} else if templateId >= 4 && templateId <= 7 {
		ipfixProtoL4 = IPFIX_PROTO_L4_TCP
		templateId = templateId - 4
	} else if templateId >= 8 && templateId <= 11 {
		ipfixProtoL4 = IPFIX_PROTO_L4_UDP
		templateId = templateId - 8
	} else if templateId >= 12 && templateId <= 15 {
		ipfixProtoL4 = IPFIX_PROTO_L4_SCTP
		templateId = templateId - 12
	} else {
		ipfixProtoL4 = IPFIX_PROTO_L4_ICMP
		templateId = templateId - 16
	}
	// tunnel ?
	if templateId >= 0 && templateId <= 1 {
		ipfixProtoTunnel = IPFIX_PROTO_NOT_TUNNELED
	} else {
		ipfixProtoTunnel = IPFIX_PROTO_TUNNELED
		templateId = templateId - 2
	}
	// ingress egress
	if templateId == 0 {
		ipfixFlowDirection = INGRESS_FLOW
	} else {
		ipfixFlowDirection = EGRESS_FLOW
	}
	var ovsTemplate = OVSTemplate{
		IpfixProtoL2:       ipfixProtoL2,
		IpfixProtoL3:       ipfixProtoL3,
		IpfixProtoL4:       ipfixProtoL4,
		IpfixProtoTunnel:   ipfixProtoTunnel,
		IpfixFlowDirection: ipfixFlowDirection,
	}
	return ovsTemplate
}
func L3ProtocolString(l3 int) string {
	nameList := map[int]string{
		0: "UNKNOWN",
		1: "IPV4",
		2: "IPV6",
	}
	return nameList[l3]
}
func L4ProtocolString(l4 int) string {
	nameList := map[int]string{
		0: "UNKNOWN",
		1: "TCP",
		2: "UDP",
		3: "SCTP",
		4: "ICMP",
	}
	return nameList[l4]
}
